#!/bin/bash
 echo -e ""
 echo -e ""
 echo -e "  ____    ____    ___   ____                 "
 echo -e " |    \  /    |  |   | /   |              "
 echo -e " |     \/     |  |   |/   /               "
 echo -e " |   |\  /|   |  |   |   /_                "
 echo -e " |   | \/ |   |  |   |\    \              "
 echo -e " |___|    |___|  |___| \____\                 "
 echo -e ""
